ALTER TABLE "Venue"
ADD COLUMN IF NOT EXISTS "venueType" TEXT NOT NULL DEFAULT 'NIGHT_CAFFE';

ALTER TABLE "Venue"
ALTER COLUMN "venueType" SET DEFAULT 'NIGHT_CAFFE';

UPDATE "Venue"
SET "venueType" = 'NIGHT_CAFFE'
WHERE "venueType" IS NULL OR "venueType" = 'CAFE';
